name: Build APK

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Clean
        run: ./gradlew clean

      - name: Build Release APK
        run: ./gradlew assembleRelease --warning-mode all    

      - name: List build outputs
        run: |
          echo "Listing build outputs directory:"
          ls -R presentation/build/outputs/apk/

      # - name: Check for APKs
      #   run: |
      #     if [ ! -f presentation/build/outputs/apk/playstore/release/presentation-release.apk ]; then
      #       echo "Release APK not found!"
      #       exit 1
      #     fi

      - name: Upload APKs
        id: upload-apks
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            presentation/build/outputs/apk/playstore/release/presentation-release.apk
            presentation/build/outputs/apk/playstore/release/presentation-release-signed.apk
            presentation/build/outputs/apk/playstore/release/presentation-release-unsigned.apk
            presentation/build/outputs/apk/accrescent/release/presentation-accrescent-release.apk
            presentation/build/outputs/apk/accrescent/release/presentation-accrescent-release-signed.apk
            presentation/build/outputs/apk/accrescent/release/presentation-accrescent-release-unsigned.apk
            presentation/build/outputs/apk/apkstore/release/presentation-apkstore-release.apk
            presentation/build/outputs/apk/apkstore/release/presentation-apkstore-release-signed.apk
            presentation/build/outputs/apk/apkstore/release/presentation-apkstore-release-unsigned.apk
            presentation/build/outputs/apk/fdroid/release/presentation-fdroid-release.apk
            presentation/build/outputs/apk/fdroid/release/presentation-fdroid-release-signed.apk
            presentation/build/outputs/apk/fdroid/release/presentation-fdroid-release-unsigned.apk
            presentation/build/outputs/apk/lite/release/presentation-lite-release.apk
            presentation/build/outputs/apk/lite/release/presentation-lite-release-signed.apk
            presentation/build/outputs/apk/lite/release/presentation-lite-release-unsigned.apk
            presentation/build/outputs/apk/playstore/release/presentation-playstore-release.apk
            presentation/build/outputs/apk/playstore/release/presentation-playstore-release-signed.apk
            presentation/build/outputs/apk/playstore/release/presentation-playstore-release-unsigned.apk

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: List build outputs for Debug
        run: |
          echo "Listing build outputs directory:"
          ls -R presentation/build/outputs/apk/

      - name: Upload Debug APK
        id: upload-debug-apk
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: |
            presentation/build/outputs/apk/playstore/debug/presentation-debug.apk
            presentation/build/outputs/apk/accrescent/debug/presentation-accrescent-debug.apk
            presentation/build/outputs/apk/apkstore/debug/presentation-apkstore-debug.apk
            presentation/build/outputs/apk/fdroid/debug/presentation-fdroid-debug.apk
            presentation/build/outputs/apk/lite/debug/presentation-lite-debug.apk
            presentation/build/outputs/apk/playstore/debug/presentation-playstore-debug.apk

      # - name: Build Release APK for Playstore
      #   run: ./gradlew assemblePlaystoreRelease

      # - name: List build outputs for Playstore Release
      #   run: |
      #     echo "Listing build outputs directory:"
      #     ls -R presentation/build/outputs/apk/

      # - name: Upload Playstore Release APK
      #   id: upload-playstore-release
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: app-playstore-release
      #     path: presentation/build/outputs/apk/playstore/release/presentation-playstore-release-unsigned.apk

      - name: Get next version
        id: get_version
        run: |
          tags=$(git tag -l 'v*' | sort -V)
          if [ -z "$tags" ]; then
            echo "next_version=1.0.0" >> $GITHUB_OUTPUT
          else
            latest_tag=$(echo "$tags" | tail -n 1)
            version=${latest_tag#v}
            IFS='.' read -r major minor patch <<< "$version"
            new_patch=$((patch + 1))
            new_version="${major}.${minor}.${new_patch}"
            echo "next_version=${new_version}" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git tag -a "v${{ steps.get_version.outputs.next_version }}" -m "Auto release v${{ steps.get_version.outputs.next_version }}"
          git push origin "v${{ steps.get_version.outputs.next_version }}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        with:
          files: |
            presentation/build/outputs/apk/playstore/debug/presentation-debug.apk
            presentation/build/outputs/apk/accrescent/debug/presentation-accrescent-debug.apk
            presentation/build/outputs/apk/apkstore/debug/presentation-apkstore-debug.apk
            presentation/build/outputs/apk/fdroid/debug/presentation-fdroid-debug.apk
            presentation/build/outputs/apk/lite/debug/presentation-lite-debug.apk
            presentation/build/outputs/apk/playstore/debug/presentation-playstore-debug.apk            
            presentation/build/outputs/apk/lite/release/presentation-lite-release.apk
            presentation/build/outputs/apk/lite/release/presentation-lite-release-signed.apk
            presentation/build/outputs/apk/lite/release/presentation-lite-release-unsigned.apk
            presentation/build/outputs/apk/fdroid/release/presentation-fdroid-release.apk
            presentation/build/outputs/apk/fdroid/release/presentation-fdroid-release-signed.apk
            presentation/build/outputs/apk/fdroid/release/presentation-fdroid-release-unsigned.apk
            presentation/build/outputs/apk/apkstore/release/presentation-apkstore-release.apk
            presentation/build/outputs/apk/apkstore/release/presentation-apkstore-release-signed.apk
            presentation/build/outputs/apk/apkstore/release/presentation-apkstore-release-unsigned.apk
            presentation/build/outputs/apk/accrescent/release/presentation-accrescent-release.apk
            presentation/build/outputs/apk/accrescent/release/presentation-accrescent-release-signed.apk
            presentation/build/outputs/apk/accrescent/release/presentation-accrescent-release-unsigned.apk
            presentation/build/outputs/apk/playstore/release/presentation-playstore-release.apk
            presentation/build/outputs/apk/playstore/release/presentation-playstore-release-signed.apk
            presentation/build/outputs/apk/playstore/release/presentation-playstore-release-unsigned.apk
          tag_name: v${{ steps.get_version.outputs.next_version }}
          name: Release v${{ steps.get_version.outputs.next_version }}
          body: |
            Build from branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}

